# Numpy

## 1 Introduction to Numpy

* packages  for  numerical  computing;
* ndarray (N-dimensional array), an efficient multidimensional array;
* fast mathematical operations.

### 1.1 ndarray

In [1]:
import numpy as np
arr1=np.array([1,2,3])
arr1

array([1, 2, 3])

In [2]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
arr2.shape

(2, 3)

In [4]:
arr2.dtype

dtype('int32')

### 1.2 Creating ndarrays

In [5]:
arr3 = np.array(range(12))
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
arr3.shape

(12,)

In [7]:
arr3.dtype

dtype('int32')

In [8]:
arr4 = np.array(range(3,28)).reshape((5,5))
arr4

array([[ 3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27]])

In [9]:
arr4.shape

(5, 5)

In [10]:
arr4.dtype

dtype('int32')

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

## 2 Axes, indexing, slicing

In [14]:
arr1 = np.array(range(12)).reshape((3,2,2))
arr1

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [15]:
arr1[0]

array([[0, 1],
       [2, 3]])

![title](1.jpg)

In [16]:
baby0=arr1[0]
baby0

array([[0, 1],
       [2, 3]])

In [17]:
baby1=baby0[0]
baby1

array([0, 1])

In [18]:
baby1[0]

0

In [19]:
arr1

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [20]:
arr1[0,1]

array([2, 3])

In [21]:
arr1[2,1,0]

10

In [22]:
arr1[[1,2]]

array([[[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [23]:
arr1[1:3]

array([[[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [24]:
arr1[1:3,:2]

array([[[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [25]:
arr2 = np.array(range(3,30)).reshape((3,3,3))
arr2

array([[[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20]],

       [[21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [26]:
arr2[2,1,2]

26

In [27]:
arr2[:2,1:3]

array([[[ 6,  7,  8],
        [ 9, 10, 11]],

       [[15, 16, 17],
        [18, 19, 20]]])

## 3 “Vectorized” Operations

### 3.1 Basic Mathematical Operations

When a function acts on an array, the mathematical operation is applied to each entry in the array.

In [28]:
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [29]:
arr1*2

array([2, 4, 6])

In [30]:
arr2=np.array([[2,3,4],[4,5,6]])
arr2

array([[2, 3, 4],
       [4, 5, 6]])

In [31]:
arr2+2

array([[4, 5, 6],
       [6, 7, 8]])

In [32]:
arr3=np.array(range(1,7)).reshape((2,3))
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
arr2+arr3

array([[ 3,  5,  7],
       [ 8, 10, 12]])

### 3.2 Vectorized Operations

In [34]:
arr1 = np.array(range(10**6))
list1 = list(range(10**6))

In [35]:
%time for k in range(50): arr2=arr1*2

Wall time: 107 ms


In [36]:
%time for k in range(50): list2=[x*2 for x in list1]

Wall time: 5.23 s


## 3.3 Specifying the axis Keyword Argument in Sequential NumPy Functions

In [37]:
arr1= np.array([2.3,2,True])
arr1

array([2.3, 2. , 1. ])

In [38]:
arr1.dtype

dtype('float64')

In [39]:
arr1.shape

(3,)

In [40]:
np.sum(arr1)

5.3

In [41]:
arr2 = np.array([[2,32,14],[1,2,3]])
arr2

array([[ 2, 32, 14],
       [ 1,  2,  3]])

In [42]:
arr2.shape

(2, 3)

In [46]:
np.sum(arr2)

54

In [47]:
np.sum(arr2,axis=0)

array([ 3, 34, 17])

In [48]:
np.sum(arr2,axis=1)

array([48,  6])

In [49]:
arr3 = np.array(range(27)).reshape((3,3,3))
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [50]:
np.mean(arr3)

13.0

In [51]:
np.mean(arr3,axis=1)

array([[ 3.,  4.,  5.],
       [12., 13., 14.],
       [21., 22., 23.]])

In [52]:
np.max(arr3)

26

In [54]:
np.max(arr3,axis=2)

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])

# 4 Broadcasting

In [60]:
np.array([1,2,3])+ np.array([4,5,6])

array([5, 7, 9])

In [61]:
np.array([[1,2],[3,4]]) * np.array([[6,7],[8,9]])

array([[ 6, 14],
       [24, 36]])

### example1：

In [62]:
arr1 = np.array([1,2,4])
arr2 = np.array([[2,3,4],[4,5,6]])

In [63]:
arr2.shape

(2, 3)

In [64]:
arr1 + arr2

array([[ 3,  5,  8],
       [ 5,  7, 10]])

In [65]:
np.broadcast_to(arr1,(2,3))

array([[1, 2, 4],
       [1, 2, 4]])

In [66]:
arr2

array([[2, 3, 4],
       [4, 5, 6]])

In [67]:
2 + np.array([1,2,3])

array([3, 4, 5])

In [68]:
np.broadcast_to(2,3)

array([2, 2, 2])

In [75]:
arr3 = np.array([1,2,3]).reshape((3,1))
arr3

array([[1],
       [2],
       [3]])

In [76]:
arr4 = np.array([[2,3],[4,5],[6,7]])
arr4

array([[2, 3],
       [4, 5],
       [6, 7]])

In [77]:
arr4.shape

(3, 2)

In [78]:
arr3+arr4

array([[ 3,  4],
       [ 6,  7],
       [ 9, 10]])

In [79]:
np.array([1,2]) + np.array([3,4,6])

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

## Rules of Broadcasting

1 兩個array的維度相同。

arr3 : 3,1
arr4:  3,2

In [80]:
arr1 = np.array([[[1,2]],
                  [[2,3]],
                   [[4,5]]])
arr1

array([[[1, 2]],

       [[2, 3]],

       [[4, 5]]])

In [81]:
arr1.shape

(3, 1, 2)

In [82]:
arr2 = np.array(range(6)).reshape((3,2,1))
arr2

array([[[0],
        [1]],

       [[2],
        [3]],

       [[4],
        [5]]])

In [84]:
arr3=arr1 + arr2

In [85]:
arr3.shape

(3, 2, 2)

In [ ]:
arr1: 3,2,2
arr2: 3,2,2

In [86]:
arr1_b = np.broadcast_to(arr1,(3,2,2))
arr1_b

array([[[1, 2],
        [1, 2]],

       [[2, 3],
        [2, 3]],

       [[4, 5],
        [4, 5]]])

In [87]:
arr1

array([[[1, 2]],

       [[2, 3]],

       [[4, 5]]])

In [88]:
arr2_b = np.broadcast_to(arr2,(3,2,2))
arr2_b

array([[[0, 0],
        [1, 1]],

       [[2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5]]])

In [89]:
arr2

array([[[0],
        [1]],

       [[2],
        [3]],

       [[4],
        [5]]])

In [90]:
arr1_b + arr2_b

array([[[ 1,  2],
        [ 2,  3]],

       [[ 4,  5],
        [ 5,  6]],

       [[ 8,  9],
        [ 9, 10]]])

In [91]:
arr1 + arr2

array([[[ 1,  2],
        [ 2,  3]],

       [[ 4,  5],
        [ 5,  6]],

       [[ 8,  9],
        [ 9, 10]]])

In [ ]:
arr1 3,3,2
arr2   3,1

arr3: 3,1,2
arr4:   2,1

In [92]:
x = np.array([[[1,2]],[[2,3]],[[4,5]]])
x.shape

(3, 1, 2)

In [93]:
y = np.array([[0],[1],[2]])
y.shape

(3, 1)

In [94]:
z = x-y

In [95]:
z

array([[[ 1,  2],
        [ 0,  1],
        [-1,  0]],

       [[ 2,  3],
        [ 1,  2],
        [ 0,  1]],

       [[ 4,  5],
        [ 3,  4],
        [ 2,  3]]])

In [96]:
z.shape

(3, 3, 2)

In [97]:
x_b = np.broadcast_to(x,(3,3,2))
x_b

array([[[1, 2],
        [1, 2],
        [1, 2]],

       [[2, 3],
        [2, 3],
        [2, 3]],

       [[4, 5],
        [4, 5],
        [4, 5]]])

In [98]:
x

array([[[1, 2]],

       [[2, 3]],

       [[4, 5]]])

In [99]:
y

array([[0],
       [1],
       [2]])

In [101]:
y_b=np.broadcast_to(y,(3,3,2))
y_b

array([[[0, 0],
        [1, 1],
        [2, 2]],

       [[0, 0],
        [1, 1],
        [2, 2]],

       [[0, 0],
        [1, 1],
        [2, 2]]])

In [102]:
x_b-y_b

array([[[ 1,  2],
        [ 0,  1],
        [-1,  0]],

       [[ 2,  3],
        [ 1,  2],
        [ 0,  1]],

       [[ 4,  5],
        [ 3,  4],
        [ 2,  3]]])

In [103]:
x-y

array([[[ 1,  2],
        [ 0,  1],
        [-1,  0]],

       [[ 2,  3],
        [ 1,  2],
        [ 0,  1]],

       [[ 4,  5],
        [ 3,  4],
        [ 2,  3]]])

In [104]:
x

array([[[1, 2]],

       [[2, 3]],

       [[4, 5]]])

In [105]:
x[:2]

array([[[1, 2]],

       [[2, 3]]])