# pandas

In [2]:
import numpy as  np
import  pandas as pd

## Series

In [3]:
s1 = pd.Series([3,7,0-2,6])

In [4]:
s1

0    3
1    7
2   -2
3    6
dtype: int64

In [5]:
s1.values

array([ 3,  7, -2,  6], dtype=int64)

In [6]:
s1.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
type(s1)

pandas.core.series.Series

In [8]:
s2 = pd.Series([3,7,0-2,6],index = ['a','c','b','d'])
s2

a    3
c    7
b   -2
d    6
dtype: int64

In [9]:
s2.index

Index(['a', 'c', 'b', 'd'], dtype='object')

In [10]:
s2['a']

3

In [11]:
s2['d'] = 9

In [12]:
s2

a    3
c    7
b   -2
d    9
dtype: int64

In [13]:
s2[['b','a','c']]

b   -2
a    3
c    7
dtype: int64

In [14]:
s2[s2>0]

a    3
c    7
d    9
dtype: int64

In [15]:
s2*2

a     6
c    14
b    -4
d    18
dtype: int64

In [16]:
np.exp(s2)

a      20.085537
c    1096.633158
b       0.135335
d    8103.083928
dtype: float64

In [17]:
stocks1 = {'stock1':36,'stock2':51,'stock3':18,'stock4':60}

In [19]:
portfolio1 = pd.Series(stocks1)

In [20]:
portfolio1

stock1    36
stock2    51
stock3    18
stock4    60
dtype: int64

In [30]:
propensity = ['stock3','stock2','stock5','stock1']

In [31]:
portfolio2 = pd.Series(portfolio1,index=propensity)

In [32]:
portfolio2

stock3    18.0
stock2    51.0
stock5     NaN
stock1    36.0
dtype: float64

In [33]:
pd.isnull(portfolio2)

stock3    False
stock2    False
stock5     True
stock1    False
dtype: bool

In [34]:
pd.notnull(portfolio2)

stock3     True
stock2     True
stock5    False
stock1     True
dtype: bool

In [36]:
stocks3 =  {'stock1':36,'stock3':18,'stock4':60,'stock5':27}

In [37]:
portfolio3 = pd.Series(stocks3)

In [38]:
portfolio1

stock1    36
stock2    51
stock3    18
stock4    60
dtype: int64

In [39]:
portfolio3 

stock1    36
stock3    18
stock4    60
stock5    27
dtype: int64

In [40]:
portfolio1 + portfolio3 

stock1     72.0
stock2      NaN
stock3     36.0
stock4    120.0
stock5      NaN
dtype: float64

In [41]:
portfolio3.name = 'my portfoio'

In [42]:
portfolio3.index.name = 'bullishStock'

In [43]:
portfolio3

bullishStock
stock1    36
stock3    18
stock4    60
stock5    27
Name: my portfoio, dtype: int64

In [44]:
portfolio3.index= ['asset1','asset3','asset4','asset5']

In [45]:
portfolio3

asset1    36
asset3    18
asset4    60
asset5    27
Name: my portfoio, dtype: int64

# DataFrame

## create dataframe

In [46]:
df1 = pd.DataFrame(np.array([[10,11],[20,21]]))

In [47]:
df1

0   1
0  10  11
1  20  21

In [48]:
df1.shape

(2, 2)

In [49]:
df1.index

RangeIndex(start=0, stop=2, step=1)

In [50]:
df1.values

array([[10, 11],
       [20, 21]])

In [53]:
df2 = pd.DataFrame(np.array([[0,1],[2,3]]),
                  columns=['c1','c2'],
                index=['r1','r2'])

In [54]:
df2

c1  c2
r1   0   1
r2   2   3

In [56]:
np.arange(10,15)

array([10, 11, 12, 13, 14])

In [57]:
s0 = pd.Series(np.arange(10,15),index=['r0','r1','r2','r3','r4'])

In [58]:
s0

r0    10
r1    11
r2    12
r3    13
r4    14
dtype: int32

In [59]:
s1 = pd.Series(np.arange(15,20),index=['r0','r1','r2','r3','r4'])

In [60]:
s2 = pd.Series(np.arange(20,25),index=['r0','r1','r2','r3','r4'])

In [61]:
df3=pd.DataFrame()

In [62]:
df3['c0']=s0
df3['c1']=s1
df3['c2']=s2

In [63]:
df3

c0  c1  c2
r0  10  15  20
r1  11  16  21
r2  12  17  22
r3  13  18  23
r4  14  19  24

In [66]:
data = {'stock':['s01','s02','s03','s04','s05','s06'],
       'price': [45,23,98,77,11,63],
       'position':[100,200,150,300,230,320]}

In [67]:
myportfolio=pd.DataFrame(data,index = ['one','two','three','four','five','six'])

In [68]:
myportfolio

stock  price  position
one     s01     45       100
two     s02     23       200
three   s03     98       150
four    s04     77       300
five    s05     11       230
six     s06     63       320

## Retrieve a DatFrame

In [69]:
myportfolio['stock']

one      s01
two      s02
three    s03
four     s04
five     s05
six      s06
Name: stock, dtype: object

In [70]:
myportfolio.price

one      45
two      23
three    98
four     77
five     11
six      63
Name: price, dtype: int64

In [71]:
myportfolio[['stock','price']]

stock  price
one     s01     45
two     s02     23
three   s03     98
four    s04     77
five    s05     11
six     s06     63

In [72]:
myportfolio.loc['two',['stock','price']]

stock    s02
price     23
Name: two, dtype: object

In [73]:
myportfolio.iloc[1,[0,1]]

stock    s02
price     23
Name: two, dtype: object